add_files ./rocev2_src/interfaces/axi_intf.sv
add_files ./rocev2_src/interfaces/lynx_intf.sv
add_files ./rocev2_src/interfaces/roce_pkg.sv
add_files ./rocev2_src/buffer_fifo.sv
add_files ./rocev2_src/fifo.sv
add_files ./rocev2_src/icrc.sv
add_files ./rocev2_src/queue_meta.sv
add_files ./rocev2_src/rdma_flow.sv
add_files ./rocev2_src/roce_stack.sv
add_files ./rocev2_src/sp_ram_nc.sv
add_files ./wrapper_src/roce_stack_axis_to_aximm.sv
add_files ./wrapper_src/roce_stack_csr.sv
add_files ./wrapper_src/roce_stack_request_handler.sv
add_files ./wrapper_src/roce_stack_wq_manager.sv
add_files ./wrapper_src/roce_stack_wrapper.sv
add_files ./wrapper_src/dp_bram.sv